apiVersion: v1
baseDomain: lamta.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: okd4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret:  '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTY0ZTQ5NTg1ODhkNDdhMDlhNjgyZjUxMjdhN2Y4NDU6T0RIWVpUOFk4Q002QzVJUDIwN0xUOUZHMkFNQjdYTDlWNU02M0NKMkNENlNaV05QTDRURkExSEpaS0IyRkMzUQ==","email":"adam.xie@acentury.co"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTY0ZTQ5NTg1ODhkNDdhMDlhNjgyZjUxMjdhN2Y4NDU6T0RIWVpUOFk4Q002QzVJUDIwN0xUOUZHMkFNQjdYTDlWNU02M0NKMkNENlNaV05QTDRURkExSEpaS0IyRkMzUQ==","email":"adam.xie@acentury.co"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTg2NDczZWE4LTYwY2UtNDU2MC04NjZiLTI2MmEyNThjMGRhOTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBPVGcwTURZM1ltRXhaalUwWkRreU9ERTNNV05oTVRka05EbGpNekUxTXlKOS5tc1ZDMV9TNFBGSnNxdzRJY1kydzhSWktLeVNvQVZvMnJaNmhQYTlJeTcxaDdyR2VZZ2RKaXMtMkJKbWY0akU5NHAxbmRzdmliaHVpMVFpNG4yS0ozTHdEaEw1TG1xaXFvVk9fejZadWt5MW9BcmkwMDNwaVVMQS1HRHNVYk80WW1Td2YydlJMWGNKQ1ZKR24tYl9ic2s1Z1hLRjl3dV9aQnE5cEhmRVk4NkhmLVFza0ZPRW5tRmVjeW94V0JIdWgzazBlNXRmZmJ1TDhtMXZyUHN6ZEE4aERRZjJGOWlaUUlxS0dQVW1TZ2I1bTc3d2VCSkQ1SG1WYkx3TkJIaWsyZ1BwblNsYThrMEVRU3JfWmdzXy03VFg2TnpSTVNEVmhTVEVmaC15RGhoQldZdjNQTmNyTmxmTnVQT2ZkN2FhMkRGQ2tJXzhqVkhja3ZFUXJ2bW5JcWhCRFo4ci02MVhNejJkcnVrRDdRMmY1TUkzcnVneXczOFQyMmZPWWdrRkE0MU9TcmJDMjU3RHY4dFdibG5OWVp5clRTQ3ZuY1hNMUNscXJDMTVuOXh3U2U5TkUyVTF2UnA1UVo0TzdSbDNiZWJCRFlQaVRvQjg1NEpJRzk5clhXWXZNUFpNMzgybjZENUY1cWEtYjYwaHI3OTZQaEwyVGpjeFVNQlFzeG9ocEhMbGRRMWhDYXZ1bWt3dFNuMkd3X0VhLTFlNGxWSmhuVVA3MFZ5dTBYWmY1WDBqdVlqTDN3OFdhQXpLdmNLN0tmWFNpZ2k3X2ZleW91MHlwNDBBeExDUGtKVFpZdGZXUVJhbmVabVp4NEE3QUkwaENtaE1nZUk3bGZKS0RQS25Ec2RlUW03cFVQR3NWWmgtZXBpeHlsSE9JZDVSYWE0ekRLTWVxZExrclVmQQ==","email":"adam.xie@acentury.co"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTg2NDczZWE4LTYwY2UtNDU2MC04NjZiLTI2MmEyNThjMGRhOTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBPVGcwTURZM1ltRXhaalUwWkRreU9ERTNNV05oTVRka05EbGpNekUxTXlKOS5tc1ZDMV9TNFBGSnNxdzRJY1kydzhSWktLeVNvQVZvMnJaNmhQYTlJeTcxaDdyR2VZZ2RKaXMtMkJKbWY0akU5NHAxbmRzdmliaHVpMVFpNG4yS0ozTHdEaEw1TG1xaXFvVk9fejZadWt5MW9BcmkwMDNwaVVMQS1HRHNVYk80WW1Td2YydlJMWGNKQ1ZKR24tYl9ic2s1Z1hLRjl3dV9aQnE5cEhmRVk4NkhmLVFza0ZPRW5tRmVjeW94V0JIdWgzazBlNXRmZmJ1TDhtMXZyUHN6ZEE4aERRZjJGOWlaUUlxS0dQVW1TZ2I1bTc3d2VCSkQ1SG1WYkx3TkJIaWsyZ1BwblNsYThrMEVRU3JfWmdzXy03VFg2TnpSTVNEVmhTVEVmaC15RGhoQldZdjNQTmNyTmxmTnVQT2ZkN2FhMkRGQ2tJXzhqVkhja3ZFUXJ2bW5JcWhCRFo4ci02MVhNejJkcnVrRDdRMmY1TUkzcnVneXczOFQyMmZPWWdrRkE0MU9TcmJDMjU3RHY4dFdibG5OWVp5clRTQ3ZuY1hNMUNscXJDMTVuOXh3U2U5TkUyVTF2UnA1UVo0TzdSbDNiZWJCRFlQaVRvQjg1NEpJRzk5clhXWXZNUFpNMzgybjZENUY1cWEtYjYwaHI3OTZQaEwyVGpjeFVNQlFzeG9ocEhMbGRRMWhDYXZ1bWt3dFNuMkd3X0VhLTFlNGxWSmhuVVA3MFZ5dTBYWmY1WDBqdVlqTDN3OFdhQXpLdmNLN0tmWFNpZ2k3X2ZleW91MHlwNDBBeExDUGtKVFpZdGZXUVJhbmVabVp4NEE3QUkwaENtaE1nZUk3bGZKS0RQS25Ec2RlUW03cFVQR3NWWmgtZXBpeHlsSE9JZDVSYWE0ekRLTWVxZExrclVmQQ==","email":"adam.xie@acentury.co"},"registry.lamta.com:8443":{"auth":"YWRtaW46SGFyYm9yMTIzNDU=","email":""}}}'
sshKey:  'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9BZlCCbAru7O9LtY96ozqsMYRGd6hpb+ojs264BFXPnCaRHIxVusnGNNqGWKJIlKOicnjZmYppus0Uj1TNmF+uuBXq6mqnTaS1kAoHU2Ir4W3b1DIdhXEYQGuivwdqqiz+P+rDfKBj3/sQhFvuiE3BQlXkAlEgqpOvOG7Pmkq+he4VERePtTpCygiVHHWJvQNEXJZN1u5tx+nFCguU+FQ61o5+Nnb0fgQQvZCb3de65lwBAMQW8BI/azmc8sYMgWBFMzIT4IjVKU7Cch2ip2tiManQxYn/LWm+lp5F5dDS8r5pUrqKsys6E49rptgty/V+DKwAZen5n1cP/j93DmNCvzVQ6+JPiPgAFAs38oNJlpn/gLSgJghxpxqSJRNm09Ql4ScBFcyD8NicbbxSFpKy5xU4nOvLJG/liCQSORn3yNnPeKclgWQ0TNK1Wabvter9DK2AmxuLpap1OWENiPSQjQyXPPM5UdJcDhknWL+GMC2A7oUuuMwzKfRAYj+z84nqmuGZo1teRUcyeKPIIqDhyLODbeCNGIZluIFm1yCwNtRM5qg7jgvs0sd/ST/4PV6MQnQFTHukKX/LDMKKo47IjSt309dEj85LVYo5YfzZnX1JOTZC5NEw/nWVxdDsXI0SoGD8gUq/no4ngx6k4pe10X4N6KzQxTH1FTQUAdllQ== root@bastion.okd4.lamta.com'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFuTCCA6GgAwIBAgIUPmv8L7Kp8gHtvxLLdXgH/6uG6DEwDQYJKoZIhvcNAQEN
  BQAwbDELMAkGA1UEBhMCQ0ExCzAJBgNVBAgMAk9OMRAwDgYDVQQHDAdUb3JvbnRv
  MQ4wDAYDVQQKDAVvbWVyYTERMA8GA1UECwwIUGVyc29uYWwxGzAZBgNVBAMMEnJl
  Z2lzdHJ5Lm9tZXJhLmNvbTAeFw0yMjA5MjcwMjQ0MDZaFw0zMjA5MjQwMjQ0MDZa
  MGwxCzAJBgNVBAYTAkNBMQswCQYDVQQIDAJPTjEQMA4GA1UEBwwHVG9yb250bzEO
  MAwGA1UECgwFb21lcmExETAPBgNVBAsMCFBlcnNvbmFsMRswGQYDVQQDDBJyZWdp
  c3RyeS5vbWVyYS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC1
  3rUc9VITRHfDxmR2N1AXDFWZ/WbMLGduJvVeO0qa+U8aNkHK2XtUnLFGLsWvdc9e
  Ak5nURWTWSRMgyHBwBJ+bF8IS2up3LZ/oFqOwVnF0vjVc2qnHJojdOPi6Alkw5VO
  +oAZWt1/sLrRLlLpJAwfmx9TBlNnJeaj2Tr4j4x1zB3zTbifFk3MAcxWLVt7my2R
  PBkbcxWnz5KJSqlJuJudgYk0gWD6nOssDUK6WpfW13yrIfcks1JYStURn+9OVZg+
  xvhRHHv91lWchXwNJJPMDBioP7/ZhOAYirXw2d/3EJPXnEInSBl92JfG1aCrA0w7
  ZP6qoMm6CT21pEtTs3s0MfYtWRphXtLioKge9AGmQ8cav/yMHyKQtoks8awNWsYe
  LN1uMVE7xb3r8LseUnf43yn3/BpscZvfuG00vqZYSBTjcy7r5ySggnYy4sQPmqrZ
  VYh+c/4wTf3ZoW29wBGGbBoNIVLFcC94I6kLdEaRh+Q0X0+nbqnUgJdWE6ctvRHF
  Glu/0U5lbI3l8Pr0M3zlsxYhSGIs9wTAFHAQrhNe/VU8eqvQjtUaJYOP2dDf5dWf
  f3U579mdOjNa1hzgXRPF9QqUlFDOpNzLvQSbJwnjZU5rJzXprcNqebYKMDc8WgvJ
  7F2zYOM3vYWQTcCVlkRsd5C5W6Fdm9N/OCTg72nUoQIDAQABo1MwUTAdBgNVHQ4E
  FgQUeqzanAm8KsQTVH2s+y0OX/jG7hwwHwYDVR0jBBgwFoAUeqzanAm8KsQTVH2s
  +y0OX/jG7hwwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOCAgEAq0AK
  UCMsYnUg8lDM/8Mdjro85jkb8P71XOuO0+JZr9CFVlZAbLnI1kjkzgA3Qh0oAdns
  sSyg2nnVMauKIgKaiFpUReVkcqlqEZtbvzOfxgnv2WhOPB04zVvuxydBTFLnUuHO
  gPEhwk45LtW12Bda7GVkgPwnekXrEstGUXzHSe4lIrVS0NIDjlMpYBnOrU0n/6JQ
  N4ObpAYWRheDFa/DFUQVF2x1NJOKyFh/OHwclDYygm7sndB0PR9BszV3/5TYQEFr
  //dSVWEikSJqzot+jPEuHQOUewPB4HMpYrMcPapReuFUlAMK+UItvxKDH77k71nO
  1lFtgDu8XG+hB6dsGxhZ2FgraWS3T9JP4dbpxNUrpmFqqbGnoJYi08ocvJZz6SX6
  4XLVolocoaelaDcNjuGJPHDaNNxp9aVv0fgNwh5SpO55LdYRYoi5i0PFRjDoF3Jn
  sKkDOMmYOfWCHknzUwepaI0ApXSlNUFMqUgk1/Gey62slihqJmTd4CZSk9g1QPRl
  r6Zwf2XN9Rt8CBtbE7m/Tehz30O/raBzZ0oeVq6EOieRgfUxuZ94N4vlIW6U2Xji
  PvujJVLQ6u96RF1I0rFh6D2u5IclMnutlPSN9OpC2XW73/2/5rxyTten/diNUrUN
  acCdJbXI1zC0bBR95WHYcotO8dnFp72Wmi0Yk1E=
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.lamta.com:8443/openshift/okd
  source: quay.io/openshift/okd
- mirrors:
  - registry.lamta.com:8443/openshift/okd
  source: quay.io/openshift/okd-content
