Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@iptv-cloud 
iptv-cloud
/
OKD
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
OKD/opt/okd-install/4.10.0/install-config.yaml
@iptv-cloud
iptv-cloud Create install-config.yaml
Latest commit 65ad7a1 in 2 minutes
 History
 1 contributor
65 lines (65 sloc)  6.18 KB

apiVersion: v1
baseDomain: lamta.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: okd4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret:  '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTY0ZTQ5NTg1ODhkNDdhMDlhNjgyZjUxMjdhN2Y4NDU6T0RIWVpUOFk4Q002QzVJUDIwN0xUOUZHMkFNQjdYTDlWNU02M0NKMkNENlNaV05QTDRURkExSEpaS0IyRkMzUQ==","email":"adam.xie@acentury.co"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTY0ZTQ5NTg1ODhkNDdhMDlhNjgyZjUxMjdhN2Y4NDU6T0RIWVpUOFk4Q002QzVJUDIwN0xUOUZHMkFNQjdYTDlWNU02M0NKMkNENlNaV05QTDRURkExSEpaS0IyRkMzUQ==","email":"adam.xie@acentury.co"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTg2NDczZWE4LTYwY2UtNDU2MC04NjZiLTI2MmEyNThjMGRhOTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBPVGcwTURZM1ltRXhaalUwWkRreU9ERTNNV05oTVRka05EbGpNekUxTXlKOS5tc1ZDMV9TNFBGSnNxdzRJY1kydzhSWktLeVNvQVZvMnJaNmhQYTlJeTcxaDdyR2VZZ2RKaXMtMkJKbWY0akU5NHAxbmRzdmliaHVpMVFpNG4yS0ozTHdEaEw1TG1xaXFvVk9fejZadWt5MW9BcmkwMDNwaVVMQS1HRHNVYk80WW1Td2YydlJMWGNKQ1ZKR24tYl9ic2s1Z1hLRjl3dV9aQnE5cEhmRVk4NkhmLVFza0ZPRW5tRmVjeW94V0JIdWgzazBlNXRmZmJ1TDhtMXZyUHN6ZEE4aERRZjJGOWlaUUlxS0dQVW1TZ2I1bTc3d2VCSkQ1SG1WYkx3TkJIaWsyZ1BwblNsYThrMEVRU3JfWmdzXy03VFg2TnpSTVNEVmhTVEVmaC15RGhoQldZdjNQTmNyTmxmTnVQT2ZkN2FhMkRGQ2tJXzhqVkhja3ZFUXJ2bW5JcWhCRFo4ci02MVhNejJkcnVrRDdRMmY1TUkzcnVneXczOFQyMmZPWWdrRkE0MU9TcmJDMjU3RHY4dFdibG5OWVp5clRTQ3ZuY1hNMUNscXJDMTVuOXh3U2U5TkUyVTF2UnA1UVo0TzdSbDNiZWJCRFlQaVRvQjg1NEpJRzk5clhXWXZNUFpNMzgybjZENUY1cWEtYjYwaHI3OTZQaEwyVGpjeFVNQlFzeG9ocEhMbGRRMWhDYXZ1bWt3dFNuMkd3X0VhLTFlNGxWSmhuVVA3MFZ5dTBYWmY1WDBqdVlqTDN3OFdhQXpLdmNLN0tmWFNpZ2k3X2ZleW91MHlwNDBBeExDUGtKVFpZdGZXUVJhbmVabVp4NEE3QUkwaENtaE1nZUk3bGZKS0RQS25Ec2RlUW03cFVQR3NWWmgtZXBpeHlsSE9JZDVSYWE0ekRLTWVxZExrclVmQQ==","email":"adam.xie@acentury.co"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTg2NDczZWE4LTYwY2UtNDU2MC04NjZiLTI2MmEyNThjMGRhOTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBPVGcwTURZM1ltRXhaalUwWkRreU9ERTNNV05oTVRka05EbGpNekUxTXlKOS5tc1ZDMV9TNFBGSnNxdzRJY1kydzhSWktLeVNvQVZvMnJaNmhQYTlJeTcxaDdyR2VZZ2RKaXMtMkJKbWY0akU5NHAxbmRzdmliaHVpMVFpNG4yS0ozTHdEaEw1TG1xaXFvVk9fejZadWt5MW9BcmkwMDNwaVVMQS1HRHNVYk80WW1Td2YydlJMWGNKQ1ZKR24tYl9ic2s1Z1hLRjl3dV9aQnE5cEhmRVk4NkhmLVFza0ZPRW5tRmVjeW94V0JIdWgzazBlNXRmZmJ1TDhtMXZyUHN6ZEE4aERRZjJGOWlaUUlxS0dQVW1TZ2I1bTc3d2VCSkQ1SG1WYkx3TkJIaWsyZ1BwblNsYThrMEVRU3JfWmdzXy03VFg2TnpSTVNEVmhTVEVmaC15RGhoQldZdjNQTmNyTmxmTnVQT2ZkN2FhMkRGQ2tJXzhqVkhja3ZFUXJ2bW5JcWhCRFo4ci02MVhNejJkcnVrRDdRMmY1TUkzcnVneXczOFQyMmZPWWdrRkE0MU9TcmJDMjU3RHY4dFdibG5OWVp5clRTQ3ZuY1hNMUNscXJDMTVuOXh3U2U5TkUyVTF2UnA1UVo0TzdSbDNiZWJCRFlQaVRvQjg1NEpJRzk5clhXWXZNUFpNMzgybjZENUY1cWEtYjYwaHI3OTZQaEwyVGpjeFVNQlFzeG9ocEhMbGRRMWhDYXZ1bWt3dFNuMkd3X0VhLTFlNGxWSmhuVVA3MFZ5dTBYWmY1WDBqdVlqTDN3OFdhQXpLdmNLN0tmWFNpZ2k3X2ZleW91MHlwNDBBeExDUGtKVFpZdGZXUVJhbmVabVp4NEE3QUkwaENtaE1nZUk3bGZKS0RQS25Ec2RlUW03cFVQR3NWWmgtZXBpeHlsSE9JZDVSYWE0ekRLTWVxZExrclVmQQ==","email":"adam.xie@acentury.co"},"registry.omera.com:8443":{"auth":"YWRtaW46SGFyYm9yMTIzNDU=","email":""}}}'
sshKey:  'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIn8cfFF16aaGeM/HRriuegTSChGIp8e+9wmZ/ast/pJb3PXBs0yNGRDUXnDfqgYUOcp1oq7KgH0r8R2KGH3RwHR3bKXW6hwx77bmmFDYG9DQMXLRE1OcEsnWa7SLclTRzTfZHaFtXWUqJ6sC4s9DKr8L2QNwWF2bmDsmU8SADYxVCisu4vIDiutNwVYWkLbOkzvjMYIXWptwF2qTepRV31Se1F15vAj+t5Kc3sRwMwpQHyZvMWwxiwJHlzoc59NzrVV33R9mSMXMrkrseF2Of+hadn7S6DqzdLa62JlSCDb2IWqXUPMkNWGal7Bvm26m1jW7E2AaHug+Kly3kibZRCZRB/Bk2/3K0GbKFo2fwi5UFLa5QFgTwxrRUBqWkNaNxZCmylnHBIGAPGnqauUvDENN5ED+BdaDVhxjoWMPQHRcp2Wf44dgEj7n4yi/CBxEgk6+5WqzZQ+k2ZpsYk2JThix80fOz2WcMIimX45t4lWw8JunZSc0yfDn4VAKF4urVRuYfHLTifjqyKQNp3+zye69vFYSEunH2cr5xCQ8D80kKJxlAtgK7zW3YOx3ZlVAE6SqtKrg4xt6AMW+2IM7svO8KcPBcyI2xpBMgv0hxOfanzGeyhyCNdmXwrYclxcjawDK8BVK4tTEmoPjDTfhSQTiRe8UeWqjLTAYmH11/Tw== root@bastion.okd4.lamta.com'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFuTCCA6GgAwIBAgIUayOyYEukXfhvCgAqsIW8u9U1u0EwDQYJKoZIhvcNAQEN
  BQAwbDELMAkGA1UEBhMCQ0ExCzAJBgNVBAgMAk9OMRAwDgYDVQQHDAdUb3JvbnRv
  MQ4wDAYDVQQKDAVsYW10YTERMA8GA1UECwwIUGVyc29uYWwxGzAZBgNVBAMMEnJl
  Z2lzdHJ5LmxhbXRhLmNvbTAeFw0yMjA5MjgxNTUyNTBaFw0zMjA5MjUxNTUyNTBa
  MGwxCzAJBgNVBAYTAkNBMQswCQYDVQQIDAJPTjEQMA4GA1UEBwwHVG9yb250bzEO
  MAwGA1UECgwFbGFtdGExETAPBgNVBAsMCFBlcnNvbmFsMRswGQYDVQQDDBJyZWdp
  c3RyeS5sYW10YS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC4
  MKHutytQe7nVy+9cSoSedtZdnbaVnxDsGwHibm6tkeh4j83l69ZZ4V9J+Q55Rdx3
  96j5UtJFNUPEs09OBV4rNvYBQVlU5iiodIDFfGqqYfhrip+6BfgaZU3EtaALaMiu
  PE6t4+abpDuPCZK4um4tRDwOaQRIHntUKC/+YubqKqoE9PIgpuaKxYceH1Uau39b
  7WCFyAQiBQWMtWRiI3m7ySOG050CEdS4V9gUkldU+T5nZRryzeGby7mtEe8CMZC4
  aEyhwl4AybpzVBwkrxoXfiiMRj0X4zqZNF6FEcb0H4uisCkyTEpQCke/D/2NXRsY
  aCQ/cNBss9vhDZwJA6sdeuubmjmJZVIJNr7nHIT7i2HwI0bjIxws6tqqeogmkGtq
  A9486yfJGWF1SH8zUWw0Q5ENkazOr25e/vTSANUNNmfGxqwJYXBU36/KckmG/H2h
  Sh8Cg/eWjUU8P6O38yI9eVrP3L1kVjRQNj0AJLkAPv8ANnNAQSQu/SMHemaJq6l2
  EoOFS8MF4lx8/Zv9XYgwe4famHQlG5o0H3tvL8UQLt5Vx5KTZngUHdWy20TzQaXu
  Z8DjeaTHHOMIoAUnG8nH8DpiMrSB+SRX09pqBCCn0j7IPCYED4TKp3tVo3/rMr19
  +N7MKjrwXuYNBRGnSVlkIKF7CGdmXsTWoIISsG9azwIDAQABo1MwUTAdBgNVHQ4E
  FgQUBzTx3jwgdS++KRSbz+u/bfupLZQwHwYDVR0jBBgwFoAUBzTx3jwgdS++KRSb
  z+u/bfupLZQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOCAgEAhwSP
  qRXXVzFeaKB70u18tW0V261UQTP2KYMIg7oqYcUwpLUz83NWzPEoH8PTvbC493Yr
  oQm8hfifaoLnqb8y/cqoApgexlqiA3dx0a4O21K3Z1r65/IdRN2F0bhiZWilgV7x
  KcBAUCQc/tIkBcQRJ3SOgXDBnF5krMW1RQX9rJJrROJwqiNf371alMpTXjyRDwph
  c9izUzoX8m8z1sFpcLFn5bPJbdcpELIXFhotNhJqXYkrwxXzLrBJn982kiPg1QcA
  3Jilp7s4/qJeSCW7ZeYRjvmIU+liC1iTsXNCc03DfZty+07TRNwxJvleLreBvaVQ
  /sMkkk761Q4Lut4mXPiHxItByyOs4VXEvhI+w0TKGAPFDRqyFrHd0FC+G2WKhkrI
  iHAfZ2UTJ/pHlAlCUHokZTvhvmDps81qHKHfe85LybVGWb/2HSOcCUX1e3rjmpb0
  l1V0Z4Y1Nuzis3L92E91WbkXH+9C43kkDJ8wlu+Hdlqe3WHQeTcEzJmhmh35GMHF
  3eHXqM85QZk5OI6nwElZprkts8dzhSZOatdYNVzxszHPdKaELeyCoUywbsmag4lb
  Ge8Im2WeFrJ5M1RDDp+UNpvsN1zJtMakfWKUiOM2D3VNYnCTu33OR3AkTF19QPV8
  AgJyDLBbointtPQgbIB7rmu7DNR55LxHC2BLxLA=
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.lamta.com:8443/openshift/okd
  source: quay.io/openshift/okd
- mirrors:
  - registry.lamta.com:8443/openshift/okd
  source: quay.io/openshift/okd-content
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
OKD/install-config.yaml at master · iptv-cloud/OKD
